using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using OpenTK;

namespace Oxel
{
    public class WavefrontObjectExporter : IExporter
    {
        static readonly string SaveCommentBegin = "OBJ File Generated by Oxel";
        static readonly string SaveCommentEnd = new String(SaveCommentBegin.Reverse().ToArray());

        public void Save(string path, Vector4[] vertices, int[] indices)
        {
            using (FileStream fs = File.Create(path))
            {
                using (StreamWriter sw = new StreamWriter(fs))
                {
                    sw.WriteLine("# " + SaveCommentBegin);
                    sw.WriteLine();
                    sw.WriteLine("g " + Path.GetFileNameWithoutExtension(path));
                    sw.WriteLine();

                    // Write out the vertices
                    for (int i = 0, length = vertices.Length; i < length; i++)
                    {
                        Vector4 v = vertices[i];
                        sw.WriteLine("v {0} {1} {2}", v.X, v.Y, v.Z);
                    }

                    // Write out the mesh faces
                    for (int i = 0, length = indices.Length; i < length; i += 3)
                    {
                        int f1 = indices[i];
                        int f2 = indices[i + 1];
                        int f3 = indices[i + 2];
                        // The obj index is 1 based, so we need to add 1.
                        sw.WriteLine("f {0}// {1}// {2}//", f1 + 1, f2 + 1, f3 + 1);
                    }

                    sw.WriteLine();
                    sw.WriteLine("# " + SaveCommentEnd);
                }
            }
        }
    }
}
